### ISSUE TITLE
Example code import does not work in Python3

### ISSUE THREAD

**Issue by liffiton** [sim0nx/tsl2561#11]
```
$ python3
Python 3.6.1 (default, Mar 21 2017, 21:49:16)
[GCC 5.4.0] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from tsl2561 import TSL2561
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'TSL2561'
```

I believe the following does work:

```from tsl2561.tsl2561 import TSL2561```

I'm not sure, but maybe a tweak to ``__init__.py`` would make this work in both Python 2 and 3?

**Comment by sim0nx** [comment]
Thanks for reporting that!
I have fixed the import issue on python3 and pushed a new version to pypi

Please let me know should you have any further problems.

Fixed by ed4167896eb81af3bdbfa2c658d89842c9986d81
