### ISSUE TITLE
import constants error

### ISSUE THREAD

**Issue by msreed817** [sim0nx/tsl2561#8]
When running the example on my RPI2 I'm getting an import error from the: from tsl2561.constants import
My error is: ImportError: No module named constants

**Comment by sim0nx** [comment]
Are you sure that you installed it using pip or otherwise made it available within the PYTHONPATH ?

I just tried it on a fresh install on a pi1 and it is working fine.

**Comment by sim0nx** [comment]
no reply.... closing
